openapi: 3.0.0
info:
  title: ADA
  description: ADA
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://{{url}}
  - url: https://ada-checker.onrender.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: admin
  - name: admin > user domain
  - name: admin > company
  - name: admin > domain page
  - name: admin > page report
  - name: public
paths:
  /api/v1/user-domain:
    get:
      tags:
        - admin > user domain
      summary: show
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - admin > user domain
      summary: update or create
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                protocol:
                  type: string
                  example: https
                domain:
                  type: string
                  example: scodus.com
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/domain-report/{domain_id}:
    get:
      tags:
        - admin > user domain
      summary: get domain report
      security:
        - bearerAuth: []
      parameters:
        - name: domain_id
          in: path
          schema:
            type: string
          required: true
          example: 98b150ce-1b2a-4f7e-9f75-8aec13224609
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/company:
    get:
      tags:
        - admin > company
      summary: show
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - admin > company
      summary: update or create
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: https
                logo:
                  type: string
                  format: binary
                address:
                  type: string
                phone_number:
                  type: string
                city:
                  type: string
                country:
                  type: string
                contact_person_name:
                  type: string
                contact_person_designation:
                  type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/domain-page:
    get:
      tags:
        - admin > domain page
      summary: list
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - admin > domain page
      summary: create
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_domain_id:
                  type: string
                  example: 98b150ce-1b2a-4f7e-9f75-8aec13224609
                path:
                  type: string
                  example: services
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/domain-page/{domain_page_id}:
    get:
      tags:
        - admin > domain page
      summary: show
      security:
        - bearerAuth: []
      parameters:
        - name: domain_page_id
          in: path
          schema:
            type: string
          required: true
          example: 98b150f1-98d9-4377-bead-6a03cf6fb425
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - admin > domain page
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_domain_id:
                  type: string
                  example: 98b150ce-1b2a-4f7e-9f75-8aec13224609
                path:
                  type: string
                  example: asdfasdf
                _method:
                  type: string
                  example: PATCH
      security:
        - bearerAuth: []
      parameters:
        - name: domain_page_id
          in: path
          schema:
            type: string
          required: true
          example: 98b3063c-e70a-4904-81fa-0244646e11b1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - admin > domain page
      summary: delete
      security:
        - bearerAuth: []
      parameters:
        - name: domain_page_id
          in: path
          schema:
            type: string
          required: true
          example: 98b151e3-9a33-4b46-a2f9-13575fa800ed
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/validate-domain:
    post:
      tags:
        - public
      summary: validate domain
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_domain_id:
                  type: string
                  example: 98a756ba-7bed-4494-a772-bcc9de1d5d30
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/login:
    post:
      tags:
        - default
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@admin.com
                password:
                  type: string
                  example: P@ssw0rd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/logout:
    get:
      tags:
        - default
      summary: logout
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/scrap:
    post:
      tags:
        - default
      summary: test
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                url: https://scodus.com/
                standards: WCAG2AA
                includeWarnings: true
                includeNotices: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
